### ISSUE TITLE
I propose archiving the Fablo lab

### ISSUE THREAD

**Issue by ryjones** [hyperledger-labs/hyperledger-labs.github.io#235] opened 2023-05-22 16:54 UTC
[it has not had a commit since October](https://github.com/hyperledger-labs/fablo/commits/main) and the maintainers have not been active.

- hejwo: last activity 2022-10-28
- gzhk: last activity 2022-08-05
- dzikowski: last activity 2023-04-18, which was a comment on an issue

None of them are on Discord as far as I can tell.

[There are a bunch of open issues](https://github.com/hyperledger-labs/fablo/issues) and there were many dependabot PRs until I closed them. The tests do not build.

**Comment by dzikowski** [comment] 2023-05-22 17:34
Well, I think this is premature, for several reasons:
1. There is a long living branch (way too long, obviously) with experimental kubernetes support https://github.com/hyperledger-labs/fablo/pull/361 which includes CI fixes and addresses most urgent issues (like dependabot and support for newer fabric versions). It is scheduled to be released in the next two weeks. It's just quite big, not so easy to be finished at once.
2.  There is clearly defined scope on how to proceed with Kubernetes support, along with this year's Mentorship program https://wiki.hyperledger.org/display/INTERN/Improve+Kubernetes+Operators+support+for+Fablo
3. Fablo has active users. Some companies use it on daily basis.

This is a part of the roadmap from LFX Mentorship proposal for 2023:

> Before the the mentorship experimental support for Kubernetes is going to be merged and released by Fablo maintainers.
> - 1st quarter of the mentorship focuses on getting mentee familiar with Fablo and writing automatic tests
> - 2nd and 3rd quarter of the mentorship focus on improving Fablo by resolving found issues and improving our tests base
> - We expect at least two new Fablo releases, after 2nd and 3rd quarter of the mentorship

Fablo just lost its initial momentum, but I think this is still very valuable projects and should not be archived. I think the way we can improve is to take care more on some decluttering GitHub issues and improve transparency and communication.

**Comment by ryjones** [comment] 2023-05-22 17:53
OK. Could you take a whack at fixing the ESLINT issues and merging some trivial pull requests? Also, probably update the maintainers.md, since the other two seem to be emeritus now

**Comment by Hejwo** [comment] 2023-05-22 18:06
Hello @ryjones,
also from my side: 

1. I can confirm Jakub's words. Since we both have pretty busy daily schedule we've decided to focus only on biggest topic. That is Kubernetes Operators, which is not a simple task as in Fablo we try to deliver only features that are well tested, supported and stable.  
2. Communication channels: We are in touch with Jakub and we're using Slack both for our internal discussions and mentorship purposes. 

Ps. Should we also be present on Discord? We where not aware that such communication channel exists.

**Comment by ryjones** [comment] 2023-05-22 18:23
@Hejwo Please use discord, not slack. [here is the invite link](https://discord.gg/hyperledger) and [here is the Fablo channel](https://discord.com/channels/905194001349627914/1109190949394989127)

**Comment by Hejwo** [comment] 2023-05-22 19:46
@ryjones thank you for the invitation, joined the proper server and channel.  
Will also look at the breaking pipeline and DependaBot.

Also idea for the future - information about Discord has _never_ reached us.  
Maybe it's worth to put it in some common manual for maintainers or make it a checked requirement?  
I'm wondering how many people might be in similar situation and somehow lost it in the noise.

**Closed** 2023-07-24 21:07 UTC
